#############################################################################
# Makefile for building: tetris
# Generated by qmake (3.1) (Qt 5.13.0)
# Project:  tetris.pro
# Template: app
# Command: /Users/prinz/Qt/5.13.0/clang_64/bin/qmake -o Makefile tetris.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I. -I../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers -I../../../../Qt/5.13.0/clang_64/lib/QtGui.framework/Headers -I../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers -Imoc -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AGL.framework/Headers -I../../../../Qt/5.13.0/clang_64/mkspecs/macx-clang -F/Users/prinz/Qt/5.13.0/clang_64/lib
QMAKE         = /Users/prinz/Qt/5.13.0/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/prinz/Qt/5.13.0/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/prinz/Qt/5.13.0/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = tetris1.0.0
DISTDIR = /Users/prinz/Workspace/qt/Examples/tetris/obj/tetris1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/prinz/Qt/5.13.0/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/prinz/Qt/5.13.0/clang_64/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = block.cpp \
		gameoverscreen.cpp \
		gamescreen.cpp \
		gameview.cpp \
		main.cpp \
		pausescreen.cpp \
		uimanager.cpp \
		welcomescreen.cpp qrc_resources.cpp \
		moc/moc_gameoverscreen.cpp \
		moc/moc_gamescreen.cpp \
		moc/moc_gameview.cpp \
		moc/moc_pausescreen.cpp \
		moc/moc_uimanager.cpp \
		moc/moc_welcomescreen.cpp
OBJECTS       = obj/block.o \
		obj/gameoverscreen.o \
		obj/gamescreen.o \
		obj/gameview.o \
		obj/main.o \
		obj/pausescreen.o \
		obj/uimanager.o \
		obj/welcomescreen.o \
		obj/qrc_resources.o \
		obj/moc_gameoverscreen.o \
		obj/moc_gamescreen.o \
		obj/moc_gameview.o \
		obj/moc_pausescreen.o \
		obj/moc_uimanager.o \
		obj/moc_welcomescreen.o
DIST          = ../../../../Qt/5.13.0/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/qdevice.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/5.13.0/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/5.13.0/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/5.13.0/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt/5.13.0/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.13.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/5.13.0/clang_64/mkspecs/common/clang.conf \
		../../../../Qt/5.13.0/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt/5.13.0/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/toolchain.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/qml_debug.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/mac/mac.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/qt.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/resources.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/moc.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/uic.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/qmake_use.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/file_copies.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/lex.prf \
		tetris.pro block.h \
		gameoverscreen.h \
		gamescreen.h \
		gameview.h \
		pausescreen.h \
		uimanager.h \
		welcomescreen.h block.cpp \
		gameoverscreen.cpp \
		gamescreen.cpp \
		gameview.cpp \
		main.cpp \
		pausescreen.cpp \
		uimanager.cpp \
		welcomescreen.cpp
QMAKE_TARGET  = tetris
DESTDIR       = 
TARGET        = tetris

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.15.4
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/prinz/Workspace/qt/Examples/tetris/tetris.pro


include /Users/prinz/Qt/5.13.0/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

tetris:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: tetris.pro ../../../../Qt/5.13.0/clang_64/mkspecs/macx-clang/qmake.conf ../../../../Qt/5.13.0/clang_64/mkspecs/features/spec_pre.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/qdevice.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/device_config.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/common/unix.conf \
		../../../../Qt/5.13.0/clang_64/mkspecs/common/mac.conf \
		../../../../Qt/5.13.0/clang_64/mkspecs/common/macx.conf \
		../../../../Qt/5.13.0/clang_64/mkspecs/common/sanitize.conf \
		../../../../Qt/5.13.0/clang_64/mkspecs/common/gcc-base.conf \
		../../../../Qt/5.13.0/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../../../Qt/5.13.0/clang_64/mkspecs/common/clang.conf \
		../../../../Qt/5.13.0/clang_64/mkspecs/common/clang-mac.conf \
		../../../../Qt/5.13.0/clang_64/mkspecs/qconfig.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/qt_functions.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/qt_config.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/macx-clang/qmake.conf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/exclusive_builds.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/mac/sdk.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/toolchain.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/mac/toolchain.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/default_pre.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/mac/default_pre.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/resolve_config.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/default_post.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/mac/default_post.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/mac/objective_c.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/qml_debug.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/mac/mac.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/warn_on.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/qt.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/resources.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/moc.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/unix/opengl.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/uic.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/unix/thread.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/qmake_use.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/file_copies.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/mac/rez.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/testcase_targets.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/exceptions.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/yacc.prf \
		../../../../Qt/5.13.0/clang_64/mkspecs/features/lex.prf \
		tetris.pro \
		resources.qrc \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../../../Qt/5.13.0/clang_64/lib/QtGui.framework/QtGui.prl \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile tetris.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
../../../../Qt/5.13.0/clang_64/mkspecs/features/spec_pre.prf:
../../../../Qt/5.13.0/clang_64/mkspecs/qdevice.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/features/device_config.prf:
../../../../Qt/5.13.0/clang_64/mkspecs/common/unix.conf:
../../../../Qt/5.13.0/clang_64/mkspecs/common/mac.conf:
../../../../Qt/5.13.0/clang_64/mkspecs/common/macx.conf:
../../../../Qt/5.13.0/clang_64/mkspecs/common/sanitize.conf:
../../../../Qt/5.13.0/clang_64/mkspecs/common/gcc-base.conf:
../../../../Qt/5.13.0/clang_64/mkspecs/common/gcc-base-mac.conf:
../../../../Qt/5.13.0/clang_64/mkspecs/common/clang.conf:
../../../../Qt/5.13.0/clang_64/mkspecs/common/clang-mac.conf:
../../../../Qt/5.13.0/clang_64/mkspecs/qconfig.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_core.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_help.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_location.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_network.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../../Qt/5.13.0/clang_64/mkspecs/features/qt_functions.prf:
../../../../Qt/5.13.0/clang_64/mkspecs/features/qt_config.prf:
../../../../Qt/5.13.0/clang_64/mkspecs/macx-clang/qmake.conf:
../../../../Qt/5.13.0/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../../Qt/5.13.0/clang_64/mkspecs/features/exclusive_builds.prf:
../../../../Qt/5.13.0/clang_64/mkspecs/features/mac/sdk.prf:
../../../../Qt/5.13.0/clang_64/mkspecs/features/toolchain.prf:
../../../../Qt/5.13.0/clang_64/mkspecs/features/mac/toolchain.prf:
../../../../Qt/5.13.0/clang_64/mkspecs/features/default_pre.prf:
../../../../Qt/5.13.0/clang_64/mkspecs/features/mac/default_pre.prf:
../../../../Qt/5.13.0/clang_64/mkspecs/features/resolve_config.prf:
../../../../Qt/5.13.0/clang_64/mkspecs/features/default_post.prf:
../../../../Qt/5.13.0/clang_64/mkspecs/features/mac/default_post.prf:
../../../../Qt/5.13.0/clang_64/mkspecs/features/mac/objective_c.prf:
../../../../Qt/5.13.0/clang_64/mkspecs/features/qml_debug.prf:
../../../../Qt/5.13.0/clang_64/mkspecs/features/mac/mac.prf:
../../../../Qt/5.13.0/clang_64/mkspecs/features/warn_on.prf:
../../../../Qt/5.13.0/clang_64/mkspecs/features/qt.prf:
../../../../Qt/5.13.0/clang_64/mkspecs/features/resources.prf:
../../../../Qt/5.13.0/clang_64/mkspecs/features/moc.prf:
../../../../Qt/5.13.0/clang_64/mkspecs/features/unix/opengl.prf:
../../../../Qt/5.13.0/clang_64/mkspecs/features/uic.prf:
../../../../Qt/5.13.0/clang_64/mkspecs/features/unix/thread.prf:
../../../../Qt/5.13.0/clang_64/mkspecs/features/qmake_use.prf:
../../../../Qt/5.13.0/clang_64/mkspecs/features/file_copies.prf:
../../../../Qt/5.13.0/clang_64/mkspecs/features/mac/rez.prf:
../../../../Qt/5.13.0/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../../../Qt/5.13.0/clang_64/mkspecs/features/testcase_targets.prf:
../../../../Qt/5.13.0/clang_64/mkspecs/features/exceptions.prf:
../../../../Qt/5.13.0/clang_64/mkspecs/features/yacc.prf:
../../../../Qt/5.13.0/clang_64/mkspecs/features/lex.prf:
tetris.pro:
resources.qrc:
../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../../../Qt/5.13.0/clang_64/lib/QtGui.framework/QtGui.prl:
../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile tetris.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE


all: Makefile tetris

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents resources.qrc $(DISTDIR)/
	$(COPY_FILE) --parents ../../../../Qt/5.13.0/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents block.h gameoverscreen.h gamescreen.h gameview.h pausescreen.h uimanager.h welcomescreen.h $(DISTDIR)/
	$(COPY_FILE) --parents block.cpp gameoverscreen.cpp gamescreen.cpp gameview.cpp main.cpp pausescreen.cpp uimanager.cpp welcomescreen.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode $(EXPORT__PRO_FILE_)

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_resources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_resources.cpp
qrc_resources.cpp: resources.qrc \
		../../../../Qt/5.13.0/clang_64/bin/rcc \
		assets/styles/style.qss
	/Users/prinz/Qt/5.13.0/clang_64/bin/rcc -name resources resources.qrc -o qrc_resources.cpp

compiler_moc_predefs_make_all: moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc/moc_predefs.h
moc/moc_predefs.h: ../../../../Qt/5.13.0/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wall -W -dM -E -o moc/moc_predefs.h ../../../../Qt/5.13.0/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc/moc_gameoverscreen.cpp moc/moc_gamescreen.cpp moc/moc_gameview.cpp moc/moc_pausescreen.cpp moc/moc_uimanager.cpp moc/moc_welcomescreen.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_gameoverscreen.cpp moc/moc_gamescreen.cpp moc/moc_gameview.cpp moc/moc_pausescreen.cpp moc/moc_uimanager.cpp moc/moc_welcomescreen.cpp
moc/moc_gameoverscreen.cpp: gameoverscreen.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QFrame \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QVBoxLayout \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		moc/moc_predefs.h \
		../../../../Qt/5.13.0/clang_64/bin/moc
	/Users/prinz/Qt/5.13.0/clang_64/bin/moc $(DEFINES) --include /Users/prinz/Workspace/qt/Examples/tetris/moc/moc_predefs.h -I/Users/prinz/Qt/5.13.0/clang_64/mkspecs/macx-clang -I/Users/prinz/Workspace/qt/Examples/tetris -I/Users/prinz/Workspace/qt/Examples/tetris -I/Users/prinz/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers -I/Users/prinz/Qt/5.13.0/clang_64/lib/QtGui.framework/Headers -I/Users/prinz/Qt/5.13.0/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/prinz/Qt/5.13.0/clang_64/lib gameoverscreen.h -o moc/moc_gameoverscreen.cpp

moc/moc_gamescreen.cpp: gamescreen.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QLCDNumber \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		gameview.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		block.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/QTimeLine \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/qtimeline.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItemAnimation \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitemanimation.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		moc/moc_predefs.h \
		../../../../Qt/5.13.0/clang_64/bin/moc
	/Users/prinz/Qt/5.13.0/clang_64/bin/moc $(DEFINES) --include /Users/prinz/Workspace/qt/Examples/tetris/moc/moc_predefs.h -I/Users/prinz/Qt/5.13.0/clang_64/mkspecs/macx-clang -I/Users/prinz/Workspace/qt/Examples/tetris -I/Users/prinz/Workspace/qt/Examples/tetris -I/Users/prinz/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers -I/Users/prinz/Qt/5.13.0/clang_64/lib/QtGui.framework/Headers -I/Users/prinz/Qt/5.13.0/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/prinz/Qt/5.13.0/clang_64/lib gamescreen.h -o moc/moc_gamescreen.cpp

moc/moc_gameview.cpp: gameview.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		block.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/QTimeLine \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/qtimeline.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItemAnimation \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitemanimation.h \
		moc/moc_predefs.h \
		../../../../Qt/5.13.0/clang_64/bin/moc
	/Users/prinz/Qt/5.13.0/clang_64/bin/moc $(DEFINES) --include /Users/prinz/Workspace/qt/Examples/tetris/moc/moc_predefs.h -I/Users/prinz/Qt/5.13.0/clang_64/mkspecs/macx-clang -I/Users/prinz/Workspace/qt/Examples/tetris -I/Users/prinz/Workspace/qt/Examples/tetris -I/Users/prinz/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers -I/Users/prinz/Qt/5.13.0/clang_64/lib/QtGui.framework/Headers -I/Users/prinz/Qt/5.13.0/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/prinz/Qt/5.13.0/clang_64/lib gameview.h -o moc/moc_gameview.cpp

moc/moc_pausescreen.cpp: pausescreen.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QFrame \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QVBoxLayout \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		moc/moc_predefs.h \
		../../../../Qt/5.13.0/clang_64/bin/moc
	/Users/prinz/Qt/5.13.0/clang_64/bin/moc $(DEFINES) --include /Users/prinz/Workspace/qt/Examples/tetris/moc/moc_predefs.h -I/Users/prinz/Qt/5.13.0/clang_64/mkspecs/macx-clang -I/Users/prinz/Workspace/qt/Examples/tetris -I/Users/prinz/Workspace/qt/Examples/tetris -I/Users/prinz/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers -I/Users/prinz/Qt/5.13.0/clang_64/lib/QtGui.framework/Headers -I/Users/prinz/Qt/5.13.0/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/prinz/Qt/5.13.0/clang_64/lib pausescreen.h -o moc/moc_pausescreen.cpp

moc/moc_uimanager.cpp: uimanager.h \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QStackedLayout \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qstackedlayout.h \
		gamescreen.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QLCDNumber \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		gameview.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		block.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/QTimeLine \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/qtimeline.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItemAnimation \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitemanimation.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		pausescreen.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QFrame \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QVBoxLayout \
		gameoverscreen.h \
		welcomescreen.h \
		moc/moc_predefs.h \
		../../../../Qt/5.13.0/clang_64/bin/moc
	/Users/prinz/Qt/5.13.0/clang_64/bin/moc $(DEFINES) --include /Users/prinz/Workspace/qt/Examples/tetris/moc/moc_predefs.h -I/Users/prinz/Qt/5.13.0/clang_64/mkspecs/macx-clang -I/Users/prinz/Workspace/qt/Examples/tetris -I/Users/prinz/Workspace/qt/Examples/tetris -I/Users/prinz/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers -I/Users/prinz/Qt/5.13.0/clang_64/lib/QtGui.framework/Headers -I/Users/prinz/Qt/5.13.0/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/prinz/Qt/5.13.0/clang_64/lib uimanager.h -o moc/moc_uimanager.cpp

moc/moc_welcomescreen.cpp: welcomescreen.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QFrame \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QVBoxLayout \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		moc/moc_predefs.h \
		../../../../Qt/5.13.0/clang_64/bin/moc
	/Users/prinz/Qt/5.13.0/clang_64/bin/moc $(DEFINES) --include /Users/prinz/Workspace/qt/Examples/tetris/moc/moc_predefs.h -I/Users/prinz/Qt/5.13.0/clang_64/mkspecs/macx-clang -I/Users/prinz/Workspace/qt/Examples/tetris -I/Users/prinz/Workspace/qt/Examples/tetris -I/Users/prinz/Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers -I/Users/prinz/Qt/5.13.0/clang_64/lib/QtGui.framework/Headers -I/Users/prinz/Qt/5.13.0/clang_64/lib/QtCore.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/Users/prinz/Qt/5.13.0/clang_64/lib welcomescreen.h -o moc/moc_welcomescreen.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

obj/block.o: block.cpp block.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/QTimeLine \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/qtimeline.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItemAnimation \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitemanimation.h \
		../../../../Qt/5.13.0/clang_64/lib/QtGui.framework/Headers/QBrush \
		../../../../Qt/5.13.0/clang_64/lib/QtGui.framework/Headers/qbrush.h \
		../../../../Qt/5.13.0/clang_64/lib/QtGui.framework/Headers/QPen \
		../../../../Qt/5.13.0/clang_64/lib/QtGui.framework/Headers/qpen.h \
		../../../../Qt/5.13.0/clang_64/lib/QtGui.framework/Headers/QPainter \
		../../../../Qt/5.13.0/clang_64/lib/QtGui.framework/Headers/qpainter.h \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/QVariant \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/qvariant.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/block.o block.cpp

obj/gameoverscreen.o: gameoverscreen.cpp gameoverscreen.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QFrame \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QVBoxLayout \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsBlurEffect \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/gameoverscreen.o gameoverscreen.cpp

obj/gamescreen.o: gamescreen.cpp gamescreen.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QLCDNumber \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		gameview.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		block.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/QTimeLine \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/qtimeline.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItemAnimation \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitemanimation.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/gamescreen.o gamescreen.cpp

obj/gameview.o: gameview.cpp gameview.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		block.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/QTimeLine \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/qtimeline.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItemAnimation \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitemanimation.h \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/qdebug.h \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/QRandomGenerator \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/qrandom.h \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/QTimer \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/qtimer.h \
		../../../../Qt/5.13.0/clang_64/lib/QtGui.framework/Headers/QKeyEvent \
		../../../../Qt/5.13.0/clang_64/lib/QtGui.framework/Headers/qevent.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/gameview.o gameview.cpp

obj/main.o: main.cpp ../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		uimanager.h \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QStackedLayout \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qstackedlayout.h \
		gamescreen.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QLCDNumber \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		gameview.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		block.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/QTimeLine \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/qtimeline.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItemAnimation \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitemanimation.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		pausescreen.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QFrame \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QVBoxLayout \
		gameoverscreen.h \
		welcomescreen.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/main.o main.cpp

obj/pausescreen.o: pausescreen.cpp pausescreen.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QFrame \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QVBoxLayout \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsBlurEffect \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/pausescreen.o pausescreen.cpp

obj/uimanager.o: uimanager.cpp uimanager.h \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/QObject \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QHBoxLayout \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QStackedLayout \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qstackedlayout.h \
		gamescreen.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QWidget \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qwidget.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QLCDNumber \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qlcdnumber.h \
		gameview.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsView \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsview.h \
		block.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsRectItem \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitem.h \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/QTimeLine \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/qtimeline.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsItemAnimation \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicsitemanimation.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		pausescreen.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QFrame \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QVBoxLayout \
		gameoverscreen.h \
		welcomescreen.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qapplication.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsBlurEffect \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/QFile \
		../../../../Qt/5.13.0/clang_64/lib/QtCore.framework/Headers/qfile.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/uimanager.o uimanager.cpp

obj/welcomescreen.o: welcomescreen.cpp welcomescreen.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QFrame \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qframe.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QLabel \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qlabel.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QPushButton \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qpushbutton.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QVBoxLayout \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qboxlayout.h \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/QGraphicsBlurEffect \
		../../../../Qt/5.13.0/clang_64/lib/QtWidgets.framework/Headers/qgraphicseffect.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/welcomescreen.o welcomescreen.cpp

obj/qrc_resources.o: qrc_resources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/qrc_resources.o qrc_resources.cpp

obj/moc_gameoverscreen.o: moc/moc_gameoverscreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_gameoverscreen.o moc/moc_gameoverscreen.cpp

obj/moc_gamescreen.o: moc/moc_gamescreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_gamescreen.o moc/moc_gamescreen.cpp

obj/moc_gameview.o: moc/moc_gameview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_gameview.o moc/moc_gameview.cpp

obj/moc_pausescreen.o: moc/moc_pausescreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_pausescreen.o moc/moc_pausescreen.cpp

obj/moc_uimanager.o: moc/moc_uimanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_uimanager.o moc/moc_uimanager.cpp

obj/moc_welcomescreen.o: moc/moc_welcomescreen.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o obj/moc_welcomescreen.o moc/moc_welcomescreen.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

